# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    ignore:
      # Jersey uses the same property name (jersey.version) in jaxrs2/3/4 at different majors.
      # Per-module entries below handle jersey updates independently.
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
      # JAXB impl at 2.x (jaxb, soap) and 4.x (jaxb-jakarta, soap-jakarta)
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
        update-types: ["version-update:semver-major"]
      # SAAJ impl at 1.x (soap) and 3.x (soap-jakarta)
      - dependency-name: "com.sun.xml.messaging.saaj:saaj-impl"
        update-types: ["version-update:semver-major"]

  # Jersey 2.x for jaxrs2
  - package-ecosystem: "maven"
    directory: "/jaxrs2"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
    ignore:
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
        update-types: ["version-update:semver-major"]

  # Jersey 3.x for jaxrs3
  - package-ecosystem: "maven"
    directory: "/jaxrs3"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
    ignore:
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
        update-types: ["version-update:semver-major"]

  # Jersey 4.x for jaxrs4
  - package-ecosystem: "maven"
    directory: "/jaxrs4"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
    ignore:
      - dependency-name: "org.glassfish.jersey.core:jersey-client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.glassfish.jersey.inject:jersey-hk2"
        update-types: ["version-update:semver-major"]
